name: Flutter Build

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    paths:
      - 'bb_flutter_client/**'
      - '.github/workflows/flutter_windows_build.yml'

jobs:
  windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: bb_flutter_client
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      - run: flutter build windows --release

      - name: Create installer with Inno Setup
        shell: pwsh
        run: |
          & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' installer\biobase_setup.iss

      - uses: actions/upload-artifact@v4
        with:
          name: biobase-client-setup
          path: bb_flutter_client/installer/output/biobase-client-setup.exe

  macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: bb_flutter_client
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      - run: flutter build macos --release

      - name: Zip app bundle
        run: |
          cd build/macos/Build/Products/Release
          zip -r -y biobase-client-mac.zip biobase_client.app

      - uses: actions/upload-artifact@v4
        with:
          name: biobase-client-mac
          path: bb_flutter_client/build/macos/Build/Products/Release/biobase-client-mac.zip
